include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**/*.pb*.dart
    - lib/**/*.g.dart
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    public_member_api_docs: true
    prefer_single_quotes: true
    constant_identifier_names: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    # allow nodes to override type.
    overridden_fields: false
    use_super_parameters: true
    prefer_relative_imports: true
