name: codelessly_api
description: Flutter's layouts and widgets represented as models and JSON data. This API is used by the Codelessly Editor and CloudUI SDK to render Flutter Widgets.
version: 1.6.0
homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslyAPI

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  codelessly_json_annotation: 4.8.1
  equatable: ">=2.0.5 <3.0.0"
  vector_math: ">=2.1.4 <3.0.0"
  collection: ">=1.17.0 <2.0.0"
  meta: ">=1.9.0 <2.0.0"
  intl: '>=0.17.0 <1.0.0'

dev_dependencies:
  codelessly_json_serializable: 6.7.1+1
  build_runner: ^2.4.9
  lints: ^3.0.0

scripts: scripts.yaml
