name: codelessly_api
description: Codelessly Core API

version: 0.0.2

homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslyAPI
issue_tracker: https://github.com/Codelessly/CodelesslyAPI/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  vector_math: ^2.1.4
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
  lints: ^2.1.0

scripts: scripts.yaml