name: codelessly_api
description: Flutter's layouts and widgets represented as models and JSON data. This API is used by the Codelessly Editor and CloudUI SDK to render Flutter Widgets.

version: 0.0.3

homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslyAPI

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ">=2.0.5 <3.0.0"
  json_annotation: ^4.8.1
  vector_math: ">=2.1.4 <3.0.0"
  collection: ">=1.17.0 <2.0.0"

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0
  lints: ^2.1.1

scripts: scripts.yaml