name: codelessly_api
description: Codelessly Core API

version: 0.0.1

homepage: https://codelessly.com/
repository: https://github.com/Codelessly/CodelesslyAPI
issue_tracker: https://github.com/Codelessly/CodelesslyAPI/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  vector_math: ^2.1.4
  collection: ^1.17.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2
  lints: ^2.0.1

scripts: scripts.yaml